### ISSUE TITLE
No module named 'maidenhead' when installed

### ISSUE THREAD

**Issue by PeterSprague** [m0iax/JS8CallUtilities_V2#17]
Running in Debian Bullseye on AMD64.  Using Python 3.9 installed in venv
$ . venv/bin/activate
$ pip install -U pip
$ pip3 install -r requirements.txt

$ pip install -U maidenhead
Requirement already satisfied

$ pip show maidenhead
Name: maidenhead
Version: 1.6.0
Summary: Maidenhead Locator, Lat Lon coordinate convertor
Home-page: https://github.com/space-physics/maidenhead
Author: Michael Hirsch; Henri Kuiper
Author-email: scivision@users.noreply.github.com
License: UNKNOWN
Location: /home/XDR/Software/JS8Call/venv/lib/python3.9/site-packages
Requires: 
Required-by: 

$ ./JS8CallUtils_v2.py
Traceback (most recent call last):
  File "/home/XDR/Software/JS8Call/JS8CallUtilities_V2/./JS8CallUtils_v2.py", line 8, in <module>
    import gpsdGPSListener
  File "/home/XDR/Software/JS8Call/JS8CallUtilities_V2/gpsdGPSListener.py", line 13, in <module>
    import maidenhead as mh
ModuleNotFoundError: No module named 'maidenhead'

$ python
'>>>' import maidenhead as mh
'>>>'

**Comment by PeterSprague** [comment]
Fixed with shebang edit
#! /usr/bin/python3 --> #!/usr/bin/env python3

Will submit PR, but not sure if will be picked up so can apply the fix on local code before running

**Comment by PeterSprague** [comment]
added to code, closed
