### ISSUE TITLE
JS8CallUtils_v2.py freezes when I click Send Grid to JS8Call

### ISSUE THREAD

**Issue by strohmy** [m0iax/JS8CallUtilities_V2#8]
On Linux with Raspberry Pi, the program freezes when I click Send Grid to JS8Call. I can keyboard interrupt a few times to kill the app, and it returns the following:

`
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "./JS8CallUtilities/JS8CallUtils_v2.py", line 312, in <lambda>
    self.setJS8CallGridButton = Button(self, text="Send Grid to JS8Call", command=lambda: controller.sendGridToJS8Call(gridrefEntry.get()), bg="white")
  File "./JS8CallUtilities/JS8CallUtils_v2.py", line 597, in sendGridToJS8Call
    self.api.sendGridToJS8Call(gridText, status)
  File "/home/pi/JS8CallUtilities/js8callAPIsupport.py", line 87, in sendGridToJS8Call
    self.sendMessageAndClose(TYPE_STATION_SETGRID, gridText)
  File "/home/pi/JS8CallUtilities/js8callAPIsupport.py", line 70, in sendMessageAndClose
    content, addr = self.sock.recvfrom(65500)
KeyboardInterrupt
^CEnd of line
Traceback (most recent call last):
  File "./JS8CallUtilities/JS8CallUtils_v2.py", line 926, in <module>
    app.mainloop()
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1283, in mainloop
    self.tk.mainloop(n)
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1700, in __call__
    def __call__(self, *args):
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
`

![Screen Shot 2020-08-23 at 9 45 23 AM](https://user-images.githubusercontent.com/3008193/90983867-2fb30200-e526-11ea-8f99-1ee07f06c63d.png)

**Comment by m0iax** [comment]
Is the UDP port value in settings the same as in the JS8Call settings? Check that IP address are the same too.
Let me know if this doesn’t help and I will investigate further.
Thanks!

**Comment by strohmy** [comment]
Good shout, m0iax. I had let an errant mousewheel turn change the UDP in JS8Call. Thank you.
